#!/usr/bin/env python3
"""
Display the full prompt generated by prompt.py
Shows the complete system message that would be sent to an LLM for a single user request.
"""

from visual_prompting import create_image_prompt_template


def main():
    """Display a single comprehensive prompt example."""
    print("🔍 COMPLETE IMAGE GENERATION PROMPT")
    print("=" * 80)
    print("Sample User Request: 'Create a professional portrait of a business executive in a modern office'")
    print("=" * 80)

    # Create template and format with sample input
    template = create_image_prompt_template()
    messages = template.format_messages(media_type="image", user_request="Create a professional portrait of a business executive in a modern office")

    print("\nSYSTEM MESSAGE:")
    print("-" * 40)
    print(messages[0].content)

    print(f"\n{'='*80}")
    print("HUMAN MESSAGE:")
    print("-" * 40)
    print(messages[1].content)

    print(f"\n{'='*80}")
    print("📊 PROMPT STATISTICS:")
    print(f"System Message Length: {len(messages[0].content):,} characters")
    print(f"Human Message Length: {len(messages[1].content):,} characters")
    print(f"Total Prompt Length: {len(messages[0].content) + len(messages[1].content):,} characters")

    print(f"\n✨ This is the complete prompt your LLM would receive!")
    print("The system message contains comprehensive instructions for generating")
    print("professional-quality structured prompts for image generation.")


if __name__ == "__main__":
    main()
